# Site settings
title: SESYNC Brown Bag Lunch Seminars
email: itrequests@sesync.org
description: "SESYNC Brown Bag Lunch Seminars"
baseurl: "http://sesync-ci.github.io/brown-bag-lessons"
url: "http://www.sesync.org"
twitter_username: sesync
github_username:  SESYNC-ci

# Build settings
markdown: kramdown
permalink: pretty
